### ISSUE TITLE
package installation error

### ISSUE THREAD

**Issue by marvel479** [PSSUN/Rcirc#2]
I am trying to install this package, but gives me the following error:

Error : (converted from warning) unable to re-encode 'rCirc.R' line 52
ERROR: unable to collate and parse R files for package 'Rcirc'.

Error: Failed to install 'Rcirc' from GitHub:
  (converted from warning) installation of package ‘C:/Users/aayus/AppData/Local/Temp/RtmpspA0yH/file2f1ccbd213e/Rcirc_0.1.0.tar.gz’ had non-zero exit status

**Comment by PSSUN** [comment]
Hello, we suspect that this error is caused by Chinese in the code comments. We have removed the content that may cause errors. Please reinstall again to confirm whether the problem has been resolved.

In addition, we recommend that you use Rcirc with Linux system, because, in the prediction and translation related functions we need to call related software based on Linux system, they do not support windows operating system, but under windows system, all downstream visualization tools can use.

**Comment by marvel479** [comment]
hi! I am hoping to perform only downstream analysis for this set of data. Now when I try installing, I get the following error:
Error : (converted from warning) unable to re-encode 'showOverview.R' line 244
ERROR: unable to collate and parse R files for package 'Rcirc'

**Comment by PSSUN** [comment]
Sorry, we didn't fully fix similar errors, this time we checked all the code and removed all non-English comments. We are sure that there will be no more errors due to the same problem.

Please feel free to ask any question.
